const arrow = '<span aria-hidden="true">↗</span>';
const hair = (cls = '', eager = false) => `<picture class="${cls}"><source media="(max-width: 700px)" srcset="assets/olir-hair-mobile.webp"><img src="assets/olir-hair.webp" width="1672" height="941" alt="Long, flowing hair in the afternoon light among eucalyptus trees" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async"></picture>`;
const mortar = (cls = '', eager = false) => `<picture class="${cls}"><source media="(max-width: 700px)" srcset="assets/olir-mortar-ritual-mobile.webp"><img src="assets/olir-mortar-ritual.webp" width="1536" height="1024" alt="Rosemary, aloe vera, tea tree leaves and olive oil being blended in a stone mortar and pestle" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async"></picture>`;
const botanicals = (cls = '', eager = false) => `<picture class="${cls}"><source media="(max-width: 700px)" srcset="assets/olir-botanical-nature-mobile.webp"><img src="assets/olir-botanical-nature.webp" width="1536" height="1024" alt="Rosemary, olive oil, aloe vera and tea tree botanicals arranged in soft natural light" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async"></picture>`;
const bottle = (eager = false) => `<img src="assets/olir-bottle.webp" width="858" height="1834" alt="The full Olir sample bottle, styled with rosemary, olive leaves and aloe" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
const crumbs = (name) => `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><span aria-current="page">${name}</span></nav>`;
const intro = (eyebrow, heading, desc, theme='cream') => `<section class="page-intro ${theme}"><p class="eyebrow">${eyebrow}</p><h1>${heading}</h1><p class="intro-text">${desc}</p></section>`;
const invite = `<section class="invite"><p class="eyebrow">Be here for the beginning</p><h2>Something good<br>is <em>taking root.</em></h2><a href="product.html#waitlist" class="button">Join the first release ${arrow}</a></section>`;
const waitlist = `<section class="waitlist" id="waitlist"><div><p class="eyebrow">An invitation from Olir</p><h2>The first chapter.<br><em>Yours to discover.</em></h2><p>Be first to hear the launch date and meet our first hair oil.</p></div><div class="waitlist-form"><form name="olir-waitlist" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/thanks.html"><input type="hidden" name="form-name" value="olir-waitlist"><p class="honeypot" hidden><label>Leave this empty <input name="bot-field" tabindex="-1" autocomplete="off"></label></p><label for="waitlist-email">Your email address</label><div class="email-row"><input id="waitlist-email" name="email" type="email" autocomplete="email" placeholder="you@example.com" required maxlength="254"><button type="submit" aria-label="Join the Olir waitlist">Join the list ${arrow}</button></div></form><p class="fineprint">By joining, you agree to receive Olir launch news and occasional updates. You can ask us to remove your details through our <a href="contact.html">contact form</a>. Read our <a href="privacy.html">privacy notice</a>.</p></div></section>`;
const questions = [
  ['When can I buy Olir?', 'Our first hair oil is in development. Join the waitlist for the launch date, size, price and release details as they are confirmed.'],
  ['What is in the hair oil?', 'Rosemary, tea tree oil, aloe vera essence and olive oil are the four key ingredients in our current sample. We will share the complete ingredient list before launch.'],
  ['Is joining the waitlist a pre-order?', 'No. Joining is free and does not reserve a bottle, place an order or take a payment. It simply keeps you in the loop.'],
  ['Where will Olir ship?', 'Olir is being prepared for the Australian market. Delivery areas, costs and timeframes will be published before orders open.'],
  ['How should I use Olir?', 'The final directions, recommended amount and product precautions will be available with the first release. Our ritual page shares the thinking behind the product, rather than final application instructions.'],
  ['Is the full formula suitable for me?', 'We cannot yet confirm suitability for particular skin or scalp conditions. Please wait for the full ingredient list and precautions before deciding whether Olir is right for you.'],
  ['How do I contact Olir or leave the waitlist?', 'Use our contact form for product questions, launch enquiries or a request to remove your details from the waitlist.'],
];
const faq = (count = questions.length) => `<div class="accordion">${questions.slice(0,count).map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><div class="answer"><p>${a}</p></div></details>`).join('')}</div>`;
const ingredients = [
  ['01', 'Rosemary', 'The aromatic herb', 'Rosemary is one of the four key ingredients in our current sample. Familiar, botanical, and part of Olir’s first chapter.'],
  ['02', 'Tea tree oil', 'The essential oil', 'A distinctive botanical essential oil included in the sample blend. The complete formulation will be shared before release.'],
  ['03', 'Aloe vera essence', 'The botanical detail', 'Aloe vera essence is part of our developing formula. Its exact ingredient declaration will appear on the final ingredient list.'],
  ['04', 'Olive oil', 'The familiar oil', 'Olive oil brings a familiar botanical ingredient to the blend, alongside rosemary, tea tree oil and aloe vera essence.'],
];

export const pages = [
  {
    slug: '404', title: 'A little detour — Olir', noindex: true,
    description: 'Find your way back to Olir botanical hair care.',
    body: `<section class="success-page"><p class="eyebrow">404 / A little detour</p><h1>Let’s get you<br><em>back to your ritual.</em></h1><p>We couldn’t find this page. Discover our first hair oil or send us a note if you need a hand.</p><a href="index.html" class="button">Back to Olir ${arrow}</a><a href="contact.html" class="text-link">Contact us</a></section>`,
  },
  {
    slug: 'index', title: 'Olir — Botanical hair care. A little space for you.',
    description: 'Meet Olir, a botanical hair oil in development for your everyday ritual. Discover the ingredients and join the first-release list.',
    body: `<section class="hero"><div class="hero-copy"><p class="eyebrow">Botanical hair care · Coming soon</p><h1>A little ritual.<br>A deeper kind<br>of <em>care.</em></h1><p>From scalp to strands, a moment that belongs to you. Meet the first hair oil from Olir.</p><div class="hero-actions"><a class="button button-light" href="product.html">Discover the hair oil ${arrow}</a><a class="quiet-link" href="#waitlist">Join the first release</a></div><span class="hero-footnote">Rooted in nature. Made for your everyday.</span></div><div class="hero-art">${hair('hero-photo',true)}<span class="image-caption">The everyday, a little more unhurried.</span></div></section>
    <div class="brand-strip"><span>Botanical ingredients</span><span>Scalp-to-strand rituals</span><span>A new Australian chapter</span></div>
    <section class="editorial-intro section"><p class="eyebrow">The Olir philosophy</p><h2>Good things begin<br>with <em>a little care.</em></h2><div><p>We believe the small things deserve our attention. The ingredients we choose. The routines we return to. The quiet pleasure of making time for yourself.</p><a href="about.html" class="text-link">Our story ${arrow}</a></div></section>
    <section class="product-feature"><figure class="product-frame">${bottle()}<figcaption>The first sample · Styled for Olir</figcaption></figure><div class="product-feature-copy"><p class="eyebrow">Introducing · Our first release</p><h2>Meet your<br><em>root ritual.</em></h2><p class="product-name">The Olir Hair Oil</p><p>A botanical blend with rosemary, tea tree oil, aloe vera essence and olive oil. One product to begin. A little more care in your day.</p><div class="ingredient-tags"><span>Rosemary</span><span>Tea tree oil</span><span>Aloe vera essence</span><span>Olive oil</span></div><div class="release-line"><span>In development</span><span>First release coming soon</span></div><a href="product.html" class="button">Explore the hair oil ${arrow}</a><p class="fineprint">Join the waitlist for size, price and launch details.</p></div></section>
    <section class="ingredient-edit section"><div class="section-heading"><div><p class="eyebrow">Inside the first blend</p><h2>Familiar botanicals.<br><em>A fresh beginning.</em></h2></div><a href="ingredients.html" class="text-link">Meet the ingredients ${arrow}</a></div><div class="botanical-list">${ingredients.map(([n,name,sub])=>`<a href="ingredients.html#ingredient-${n}" class="botanical-item"><span class="eyebrow">${n} / ${sub}</span><h3>${name}</h3><span class="botanical-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></section>
    <section class="ritual-feature">${mortar('ritual-photo')}<div class="ritual-copy"><p class="eyebrow">The art of slowing down</p><h2>A few minutes.<br><em>All yours.</em></h2><p>A quiet morning. A pause at the end of the day. Hair care can be a small way of coming back to yourself.</p><a class="text-link" href="ritual.html">Discover the Olir ritual ${arrow}</a></div></section>
    <section class="faq-section section"><div><p class="eyebrow">A little clarity</p><h2>Before we<br><em>begin.</em></h2><a href="faq.html" class="text-link">All your questions ${arrow}</a></div>${faq(3)}</section>${waitlist}`,
  },
  {
    slug: 'product', title: 'The Olir Hair Oil — First release coming soon',
    description: 'Discover Olir’s first hair oil sample with rosemary, tea tree oil, aloe vera essence and olive oil. Join for launch, size and pricing details.',
    body: `${crumbs('Hair oil')}<section class="product-detail"><figure class="product-frame">${bottle(true)}<figcaption>Our sample bottle, styled for Olir. Final packaging may change.</figcaption></figure><div class="product-detail-copy"><p class="eyebrow">The first Olir release</p><h1>The Hair Oil<span class="serif-subtitle">Your root ritual.</span></h1><p class="product-lead">One small moment.<br>A whole lot of care.</p><p>Our first sample brings together rosemary, tea tree oil, aloe vera essence and olive oil. We’re preparing it for the quiet pleasure of an everyday hair-care ritual.</p><div class="release-card"><span class="eyebrow">In development</span><p>The first release is coming soon. Join for the launch date, complete ingredient list, size and price.</p><a href="#waitlist" class="button">Join the first release ${arrow}</a><span class="fineprint">Free to join. No pre-order or payment.</span></div><div class="accordion product-accordion"><details open><summary>The botanical blend <span aria-hidden="true">+</span></summary><div class="answer"><p>Rosemary · Tea tree oil · Aloe vera essence · Olive oil</p><p>These are the key ingredients in our current sample, not the full ingredient declaration. <a href="ingredients.html">Explore the ingredients</a>.</p></div></details><details><summary>Directions & product details <span aria-hidden="true">+</span></summary><div class="answer"><p>Final directions, recommended amount and precautions will be available before launch, alongside the complete ingredient list.</p></div></details><details><summary>Delivery & returns <span aria-hidden="true">+</span></summary><div class="answer"><p>Orders are not open yet. Australian delivery options and the returns process will be published before the first release. <a href="shipping-returns.html">Read our launch update</a>.</p></div></details></div></div></section><section class="statement section"><p class="eyebrow">A thoughtful beginning</p><h2>More than another step.<br><em>A moment to look forward to.</em></h2><a href="ritual.html" class="text-link">Find your ritual ${arrow}</a></section>${waitlist}`,
  },
  {
    slug: 'ingredients', title: 'The botanical edit — Olir ingredients',
    description: 'Get to know the four key ingredients in Olir’s current hair oil sample: rosemary, tea tree oil, aloe vera essence and olive oil.',
    body: `${intro('The botanical edit','Rooted in nature.<br><em>Chosen with intention.</em>','Four key ingredients in our current sample. A closer look at the beginning of our blend.','sage')}<section class="ingredient-visual">${botanicals('ingredient-photo', true)}<div><p class="eyebrow">Rosemary · Olive oil · Aloe vera · Tea tree</p><h2>Nature, seen clearly.</h2><p>Fresh botanicals, soft light and ingredient clarity give the page its own visual world.</p></div></section><section class="ingredient-story section"><div class="ingredient-story-intro"><p class="eyebrow">Our developing formula</p><h2>Know what goes<br><em>into your ritual.</em></h2><p>Ingredient clarity matters. We’ll share the complete ingredient list and product precautions before Olir becomes available to buy.</p><a class="text-link" href="product.html">Meet the hair oil ${arrow}</a></div><div class="ingredient-rows">${ingredients.map(([n,name,sub,desc])=>`<article id="ingredient-${n}"><span class="ingredient-number">${n}</span><div><p class="eyebrow">${sub}</p><h3>${name}</h3><p>${desc}</p></div></article>`).join('')}</div></section><section class="note-band"><span class="eyebrow">Full transparency</span><p>Our sample is the starting point. These four ingredients are highlights, not a substitute for the complete formula.</p><a class="text-link" href="faq.html">A few useful answers ${arrow}</a></section>${invite}`,
  },
  {
    slug: 'ritual', title: 'The Olir ritual — A little space for you',
    description: 'Discover the thinking behind the Olir hair-care ritual. A slower moment for yourself, from scalp to strands.',
    body: `<section class="story-hero"><div>${crumbs('The ritual')}<p class="eyebrow">The Olir way</p><h1>A few minutes.<br><em>All yours.</em></h1><p>Hair care can be more than something to finish. It can be a moment to come back to.</p></div>${mortar('story-hero-photo',true)}</section><section class="ritual-intro section"><p class="eyebrow">Make room for yourself</p><h2>A softer rhythm<br>for <em>everyday life.</em></h2><p>Olir is inspired by small, unhurried moments. The window open. Your phone put away. A routine that feels personal, wherever your day takes you.</p></section><section class="ritual-steps section"><article><span class="step-number">01</span><h3>Make a little space.</h3><p>Choose a moment that fits your day. A quiet start or a slower evening is enough.</p></article><article><span class="step-number">02</span><h3>Bring your attention.</h3><p>Notice the textures and scents in your routine. Let the familiar feel a little more intentional.</p></article><article><span class="step-number">03</span><h3>Keep it your own.</h3><p>A ritual does not need to be elaborate. Leave room for what feels right for you.</p></article></section><section class="note-band"><span class="eyebrow">Before using the hair oil</span><p>This is the inspiration behind Olir. Final application directions and precautions will be provided with our first release.</p><a class="text-link" href="product.html">Product details ${arrow}</a></section>${invite}`,
  },
  {
    slug: 'about', title: 'Our story — The beginning of Olir',
    description: 'Olir began with a simple idea: make room for hair care that feels personal. Meet the story behind our first botanical hair oil.',
    body: `<section class="about-hero"><div><p class="eyebrow">The beginning of Olir</p><h1>Small rituals.<br><em>Beautiful beginnings.</em></h1></div><div class="about-hero-aside"><span class="edition">01</span><p>Our first chapter<br>in botanical hair care.</p></div></section><section class="about-story section"><div><p class="eyebrow">A little space for care</p><h2>It starts with<br><em>the everyday.</em></h2></div><div class="prose"><p class="lead">The best routines are the ones that feel like yours.</p><p>Olir began with a simple idea: make room for hair care that feels personal. Our first sample is the beginning of that journey, built around familiar botanicals and the pleasure of taking time for yourself.</p><p>We’re creating Olir for the rhythms of everyday life in Australia. A quiet morning, an evening at home, a few minutes between everything else.</p><p>One hair oil to begin. Every detail worth considering.</p></div></section><div class="wide-photo botanical-wide">${botanicals()}</div><section class="values-section section"><div class="section-heading"><p class="eyebrow">What matters to us</p><h2>Less noise.<br><em>More intention.</em></h2></div><div class="values-grid"><article><span class="eyebrow">01 / Ingredients</span><h3>Clarity from the start.</h3><p>Know the ingredients in our sample, with the full formula to follow before launch.</p></article><article><span class="eyebrow">02 / Ritual</span><h3>Care that feels personal.</h3><p>A small pause in your day. Uncomplicated, unhurried and entirely yours.</p></article><article><span class="eyebrow">03 / Details</span><h3>A thoughtful beginning.</h3><p>We’re taking our first product from sample to release, one detail at a time.</p></article></div></section>${invite}`,
  },
  {
    slug: 'faq', title: 'Your questions, answered — Olir',
    description: 'Find answers about Olir’s first hair oil release, ingredient information, the waitlist and Australian delivery plans.',
    body: `${intro('Here to help','A little clarity.<br><em>Before we begin.</em>','Everything we can share about the first release, all in one place.')}<section class="care-layout section"><aside class="care-sidebar"><p class="eyebrow">Customer care</p><a href="contact.html">Contact Olir ${arrow}</a><a href="shipping-returns.html">Shipping & returns ${arrow}</a><a href="privacy.html">Privacy ${arrow}</a></aside>${faq()}</section><section class="help-band"><h2>Still curious?</h2><p>We’d love to hear from you.</p><a href="contact.html" class="button">Send us a note ${arrow}</a></section>`,
  },
  {
    slug: 'contact', title: 'Contact Olir — We’re listening',
    description: 'Get in touch with Olir for product questions, first-release enquiries or help with your waitlist details.',
    body: `${intro('Contact Olir','Good conversations<br>begin <em>here.</em>','A question about the first release? A thought to share? We’re listening.','sage')}<section class="contact-layout section"><div class="contact-copy"><p class="eyebrow">Leave us a note</p><h2>Let’s keep<br><em>in touch.</em></h2><p>Use the form for product and launch questions, or to ask us to update or remove your waitlist details.</p><p>We’ll get back to you as soon as we can.</p><a class="text-link" href="faq.html">Browse the FAQs ${arrow}</a></div><form class="contact-form" name="olir-contact" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/message-sent.html"><input type="hidden" name="form-name" value="olir-contact"><p hidden class="honeypot"><label>Leave this empty <input name="bot-field" tabindex="-1" autocomplete="off"></label></p><div class="field"><label for="contact-name">Your name</label><input id="contact-name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"></div><div class="field"><label for="contact-message">Your message</label><textarea id="contact-message" name="message" rows="5" required maxlength="5000"></textarea></div><p class="fineprint">We use these details to respond to your enquiry. Read our <a href="privacy.html">privacy notice</a>.</p><button class="button" type="submit">Send your message ${arrow}</button></form></section>`,
  },
  {
    slug: 'shipping-returns', title: 'Shipping & returns — Olir',
    description: 'Information about delivery and returns for the upcoming Olir release in Australia.',
    body: `${intro('Customer care','Good to know.<br><em>Before you order.</em>','Delivery and returns information for our first release.')}<section class="care-layout section"><aside class="care-sidebar"><p class="eyebrow">Here to help</p><a href="faq.html">FAQs ${arrow}</a><a href="contact.html">Contact Olir ${arrow}</a></aside><div class="prose policy"><h2>Our first release is coming soon.</h2><p>Olir is not yet available to purchase. There is no checkout or pre-order payment on this website.</p><h2>Delivery in Australia</h2><p>We’ll confirm delivery areas, postage costs, dispatch times and tracking details before orders open.</p><h2>Returns & product concerns</h2><p>We’ll publish the returns process and support details with the first release. If you have a question now, please <a href="contact.html">send us a note</a>.</p><h2>Stay in the loop</h2><p>The waitlist is free to join and does not place an order or reserve stock.</p><a href="product.html#waitlist" class="text-link">Join the first release ${arrow}</a></div></section>`,
  },
  {
    slug: 'privacy', title: 'Your privacy — Olir',
    description: 'How Olir uses and handles information submitted through its waitlist and contact forms.',
    body: `${intro('Your privacy','Your details.<br><em>Handled with care.</em>','How we use the information you choose to share with Olir.')}<section class="care-layout section"><aside class="care-sidebar"><p class="eyebrow">Last updated</p><p>19 September 2026</p><a href="contact.html">Privacy enquiries ${arrow}</a></aside><div class="prose policy"><h2>What you share with us</h2><p>When you join the waitlist, we collect your email address. When you send an enquiry, we collect the name, email address and message you enter in the contact form.</p><h2>How we use your details</h2><p>We use waitlist details for Olir launch news and occasional brand updates. We use contact form details to respond to your enquiry, including requests to update or remove your information.</p><h2>Our website services</h2><p>Netlify hosts this website and processes form submissions for Olir. Submissions may also be delivered to our email inbox. These services may process information outside Australia under their own privacy terms.</p><p>The website loads fonts from Google Fonts. Your browser makes requests to Google to display those fonts. Hosting and font providers may process technical details such as your IP address when you visit.</p><h2>Your choices</h2><p>You can ask us to correct or remove your details, or stop receiving Olir updates, through our <a href="contact.html">contact form</a>. Please use the email address associated with your request so we can identify the relevant details.</p><h2>Questions</h2><p>If you have a question about how your information is handled, <a href="contact.html">contact Olir</a>.</p></div></section>`,
  },
  {
    slug: 'thanks', title: 'You’re on the list — Olir', noindex: true,
    description: 'Thank you for joining the Olir first-release waitlist.',
    body: `<section class="success-page"><p class="eyebrow">You’re on the list</p><h1>Here’s to<br><em>new beginnings.</em></h1><p>Thank you for being part of Olir’s first chapter. We’ll share the launch details when they’re ready.</p><a href="product.html" class="button">Explore the hair oil ${arrow}</a><a href="index.html" class="text-link">Back to Olir</a></section>`,
  },
  {
    slug: 'message-sent', title: 'Message received — Olir', noindex: true,
    description: 'Thank you for getting in touch with Olir.',
    body: `<section class="success-page"><p class="eyebrow">Message received</p><h1>A note from you.<br><em>A reply from us.</em></h1><p>Thank you for getting in touch. We’ll respond to the email address you provided as soon as we can.</p><a href="index.html" class="button">Back to Olir ${arrow}</a></section>`,
  },
];
